### ISSUE TITLE
How to get the "gscript id"

### ISSUE THREAD

**Issue by Minipada** [wilda17/ESP8266-Google-Calendar-Arduino#1]
I tried uploading the script, deploying it. I got a url finishing by /exec, and I kept the key without this exec. Seems it's not that :/. I know it sounds silly but how do you get the gscript id at this line :

`const char *GScriptId = "gscriptid"; //replace with you gscript id`

**Comment by wilda17** [comment]
Hi,
have you set up the Google-Script? You can get the ID by clicking in the Google Script Editor: publish -> configure as Web App -> Copy the ID from the URL and then click apply.

Just copy the ID into your Arduino Sketch.
For exmaple: 
`const char *GScriptId = "AKfycbxBBSFsQjjfA-OmzbJrXAqzvTXwzcKKfr1oBfQGW37hcETrA4Z";`

**Comment by Minipada** [comment]
I already have done that but I didn't set the confidentiality to everyone, which made it not work.
Thanks !

**Comment by Minipada** [comment]
I already have done that but I didn't set the confidentiality to everyone, which made it not work.
Thanks !

**Comment by Minipada** [comment]
I already have done that but I didn't set the confidentiality to everyone, which made it not work.
Thanks !
