### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by mrohner** [wilda17/ESP8266-Google-Calendar-Arduino#3]
Hi Andreas,

When I do the 'Run -do get' step of your script I get the following error:
TypeError: Cannot call method "getEvents" of undefined. (line 13, file "Code")

Line 13 is:   var events = Cal.getEvents(Now, Later);

Any idea?

**Comment by wilda17** [comment]
Hello,
I had a look at the script. It is still working.
I tried changing the name of the calendar in line 7 and got the same error.
Do you have a calendar which matches with the name in line 7?

Please let me know if this solves your problem.

Cheers,
daniel

**Comment by mrohner** [comment]
Thanks, but yes it matches
[Calendar](https://www.dropbox.com/s/ng9qpw7o1wt7g5v/Calendar.jpg?dl=0)

I also tried the other calendars without success

**Comment by wilda17** [comment]
Hi Markus,

I can't really identify the problem. I saw that you are using the Outlook calendar - is the same calendar with the same name in the google calendar too?
Does google script have the permission to access this calendar - this is asked as soon as you start the script for the first time?

Cheers to Switzerland,
daniel

**Comment by mrohner** [comment]
You are right, I have no google calendar. Obviously this script would not do the job for outlook. I will open a google calendar just for this purpose then.
Thanks for looking into my problem.
